/** @format */

import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "../globals.css";
import NavBar from "@/components/CommonComponents/NavBar";
import Footer from "@/components/CommonComponents/Footer";
import { getDictionary } from "@/lib/dictionaries";

const lato = Lato({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
});

export const metadata: Metadata = {
  title: "TacPlay",
  description: "Generated by TacPlay",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }> | { locale: string };
}>) {
  const resolvedParams = await params;
  const locale = resolvedParams?.locale || "en";
  const dict = await getDictionary(locale);

  return (
    <html
      lang={locale}
      className={`${lato.variable} h-full antialiased`}
    >
      <body
        suppressHydrationWarning={true}
        className="min-h-full flex flex-col bg-background w-full mx-auto"
      >
        <NavBar dict={dict.nav} />
        {children}
        <Footer dict={dict.footer} navDict={dict.nav} />
      </body>
    </html>
  );
}
